In [1]:
# import pandas as pd
# Dublin = pd.read_csv("Dublin.csv")
# Limerick = pd.read_csv("Limerick.csv")
# Cork = pd.read_csv("Cork.csv")
# Athalone = pd.read_csv("Athalone.csv")
# Dundalk = pd.read_csv("Dundalk.csv")
# Letterkenny = pd.read_csv("Letterkenny.csv")
# Carlow = pd.read_csv("Carlow.csv")
# Galway = pd.read_csv("Galway.csv")


In [2]:
# frames = [Dublin, Limerick,Cork,Athalone,Dundalk,Letterkenny,Carlow,Galway]
  
# result = pd.concat(frames)
# display(result)

In [3]:
# result.to_csv('Test11.csv')

In [4]:
import pandas as pd
inprocess = pd.read_csv("InProcessDataset_2.csv")

In [5]:
inprocess.tail(5)

college                                             course   code  \
357  NUI Galway                         GY319 Mathematical Science  GY319   
358  NUI Galway                       GY405 Mechanical Engineering  GY405   
359  NUI Galway  GY320 Physics-degree options in Applied, Astro...  GY320   
360  NUI Galway          GY410 Project and Construction Management  GY410   
361  NUI Galway                                      GY301 Science  GY301   

                                                 title    course_type  \
357                               Mathematical Science  Undergraduate   
358                             Mechanical Engineering  Undergraduate   
359  Physics-degree options in Applied, Astrophysic...  Undergraduate   
360                Project and Construction Management  Undergraduate   
361                                            Science  Undergraduate   

    course_starts    fees    level  \
357     September  7408.0  Level 8   
358     September  7408.0  Level 8   
359     September  7408.0  Level 8   
360     September  7408.0  Level 8   
361     September  7408.0  Level 8   

                                                 award duration  ...  \
357         Bachelor of Science (Mathematical Science)  4 years  ...   
358               Bachelor of Engineering (Mechanical)  4 years  ...   
359  Bachelor of Science (Physics-degree options in...  4 years  ...   
360  Bachelor of Science (Project and Construction ...  4 years  ...   
361                                Bachelor of Science  4 years  ...   

                      clubs_and_societies minimum_entry_requirements:  \
357  https://socs.nuigalway.ie/societies/                         NaN   
358  https://socs.nuigalway.ie/societies/                         NaN   
359  https://socs.nuigalway.ie/societies/                         NaN   
360  https://socs.nuigalway.ie/societies/                         NaN   
361  https://socs.nuigalway.ie/societies/                         NaN   

    faculty_information:  job_opportunities_and_salary_expectations:  \
357                   NaN                                        NaN   
358                   NaN                                        NaN   
359                   NaN                                        NaN   
360                   NaN                                        NaN   
361                   NaN                                        NaN   

    course_reviews_and_testimonials: map_info:  students_accomodation_link:  \
357                              NaN        NaN                         NaN   
358                              NaN        NaN                         NaN   
359                              NaN        NaN                         NaN   
360                              NaN        NaN                         NaN   
361                              NaN        NaN                         NaN   

    clubs_and_socities_links Clubs_and_socities_links Workshops  
357                      NaN                      NaN       NaN  
358                      NaN                      NaN       NaN  
359                      NaN                      NaN       NaN  
360                      NaN                      NaN       NaN  
361                      NaN                      NaN       NaN  

[5 rows x 39 columns]

In [6]:
newdataset = inprocess[['college', 'course','code','fees','location']]

In [7]:
import numpy as np
import pandas as pd

data = np.random.randint(200,600,size=362)
df = pd.DataFrame(data, columns=['random_numbers'])

print(df)

     random_numbers
0               304
1               551
2               224
3               313
4               497
..              ...
357             302
358             323
359             571
360             406
361             371

[362 rows x 1 columns]


In [8]:
import random

In [9]:
newdataset['cao_score']=df['random_numbers']
newdataset['interest'] = pd.Series(
    random.choices(['Cricket', 'Football','Singing','Chess','Athletics'], weights=[1,1,1,1,1], k=len(df)), 
    index=df.index
)
newdataset['job_domain'] = pd.Series(
    random.choices(['IT', 'HR','Management','Support','Finance'], weights=[1, 1,1,1,1], k=len(df)), 
    index=df.index
)

C:\Users\rgons\AppData\Local\Temp/ipykernel_112568/2773462876.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdataset['cao_score']=df['random_numbers']
C:\Users\rgons\AppData\Local\Temp/ipykernel_112568/2773462876.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdataset['interest'] = pd.Series(
C:\Users\rgons\AppData\Local\Temp/ipykernel_112568/2773462876.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = v

In [10]:
newdataset.tail()
df=newdataset

In [10]:
newdataset.to_csv('Matching_data.csv')

In [11]:
df.head()

college                                  course  \
0  Technological University Dublin  TU059 Computer Science  (Data Science)   
1        University College Dublin            DN150 Biomedical Engineering   
2        University College Dublin  NQS2 Chemical & Bioprocess Engineering   
3        University College Dublin                  NVS1 Civil Engineering   
4        University College Dublin                  DN201 Computer Science   

    code    fees location  cao_score   interest  job_domain  
0  TU059  7000.0   Dublin        516   Football          HR  
1  DN150  7574.0   Dublin        407  Athletics          HR  
2   NQS2  7574.0   Dublin        335    Singing          IT  
3   NVS1  7574.0   Dublin        419  Athletics  Management  
4  DN201  7574.0   Dublin        428  Athletics  Management

In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.naive_bayes import GaussianNB
import warnings
warnings.filterwarnings("ignore")

In [ ]:
def CAO_SCORE(score):
    if  (score >= 50)  and (score <250 ) :
        return "Low"
    elif  (score >= 250)  and (score <500 ) :
        return "Medium"
    elif (score >= 500):
        return "High"
    #else: return 'Neutral'

df['cao_score'] = df['cao_score'].apply(CAO_SCORE)

In [ ]:
df ['fees'] = df ['fees'].astype(float)

In [ ]:
#df ['fees']=df.fees.fillna(df.fees.mean(), inplace=True)

In [ ]:
def Budget(Budget):
    if  (Budget > 2000)  and (Budget <4000 ) :
        return "Low"
    elif  (Budget > 4001)  and (Budget <6000 ) :
        return "Medium"
    elif (Budget > 6001)  and (Budget <8000 ) :
        return "High"
    elif (Budget > 8001) :
        return "Very High"
    else: return 'High'

df['budget'] = df['fees'].apply(Budget)

In [ ]:
df.head()

college                                  course  \
0  Technological University Dublin  TU059 Computer Science  (Data Science)   
1        University College Dublin            DN150 Biomedical Engineering   
2        University College Dublin  NQS2 Chemical & Bioprocess Engineering   
3        University College Dublin                  NVS1 Civil Engineering   
4        University College Dublin                  DN201 Computer Science   

    code    fees location cao_score  interest job_domain budget  
0  TU059  7000.0   Dublin    Medium   Cricket         IT   High  
1  DN150  7574.0   Dublin    Medium   Cricket    Finance   High  
2   NQS2  7574.0   Dublin    Medium   Cricket         HR   High  
3   NVS1  7574.0   Dublin       Low  Football         IT   High  
4  DN201  7574.0   Dublin       Low   Cricket         IT   High

In [ ]:

print("All the columns in the dataset: " , df.columns)

All the columns in the dataset:  Index(['college', 'course', 'code', 'fees', 'location', 'cao_score',
       'interest', 'job_domain', 'budget'],
      dtype='object')


In [ ]:

print('Shape of data is: %s entries and %s column'%(df.shape[0],df.shape[1]))

Shape of data is: 362 entries and 9 column


In [ ]:
df.drop('fees', axis=1, inplace=True)

In [ ]:

print("Numeric Columns in DF: \n" , df.select_dtypes(include=np.number).columns.tolist())
print("\n\nCategorical Columns in DF: \n" , df.select_dtypes(include=['object']).columns.tolist())

Numeric Columns in DF: 
 []


Categorical Columns in DF: 
 ['college', 'course', 'code', 'location', 'cao_score', 'interest', 'job_domain', 'budget']


In [ ]:
df.isnull().sum(axis=0)

college       0
course        0
code          0
location      0
cao_score     0
interest      0
job_domain    0
budget        0
dtype: int64

In [ ]:

cat_col = df[['college', 'course', 'code', 'location', 'cao_score', 'interest', 'job_domain', 'budget']]
for i in cat_col:
    print(df[i].value_counts(), end="\n\n")

Dundalk Institute of Technology                                   100
South East Technological University                                62
Technological University of the Shannon                            30
Technological University Dublin                                    29
University of Limerick                                             21
NUI Galway                                                         21
Atlantic Technological University - Donegal Letterkenny Campus     18
Munster Technological University                                   13
Griffith College                                                   11
University College Cork                                            10
Dublin City University                                              9
Carlow College, St Patrick's                                        9
Trinity College Dublin                                              8
University College Dublin                                           7
National College of 

In [ ]:
mycol = df[['cao_score', 'budget']]
for i in mycol:
    cleanup_nums = {i: {"Low": 0, "Medium": 1, "High": 2, "Very High": 3}}
    df = df.replace(cleanup_nums)



In [ ]:
cat_col = df[['location', 'interest', 'job_domain']]
for i in cat_col:
    df[i] = df[i].astype('category')
    df[i + "_code"] = df[i].cat.codes

print("\n\nList of Categorical values: \n" , df.select_dtypes(include=['object']).columns.tolist())



List of Categorical values: 
 ['college', 'course', 'code']


In [ ]:
print("\n\nList of Categorical values: \n" , df.select_dtypes(include=['object']).columns.tolist())
print("List of Numerical values: \n" , df.select_dtypes(include=np.number).columns.tolist())



List of Categorical values: 
 ['college', 'course', 'code']
List of Numerical values: 
 ['cao_score', 'budget', 'location_code', 'interest_code', 'job_domain_code']


In [ ]:
##'CAO_Score', 'Budget', 'City_code', 'interest_code', 'job_domain_code','Course_id'

In [ ]:
feed = df[['cao_score', 'budget', 'location_code', 'interest_code', 'job_domain_code','code']]

# Choosing independent vars
df_train_x = feed.drop('code',axis = 1)

# Choosing all target vars
df_train_y = feed['code']

x_train, x_test, y_train, y_test = train_test_split(df_train_x, df_train_y, test_size=.90,random_state=42)

In [ ]:
y_train = pd.DataFrame(y_train, columns = ["code"])
y_train.head()
y_test = pd.DataFrame(y_test, columns = ["code"])
y_test

code
163   DKA52
33    TU910
15    TR803
322   SE416
57    TU863
..      ...
134   US847
306   SE724
347   GY314
319   SE402
243  DKA132

[326 rows x 1 columns]

In [ ]:
#Decison Tree
dtree = DecisionTreeClassifier(random_state=60)
dtree = dtree.fit(x_train, y_train)
y_pred = dtree.predict(x_test)
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 0.009202453987730062


In [ ]:

userdata = [[1,0,4,4,1]]
ynewclass = dtree.predict(userdata)
ynew = dtree.predict_proba(userdata)
print(ynewclass)
print("Probabilities of all classes: ", ynew)
print("Probability of Predicted class : ", np.max(ynew))

['DKA103']
Probabilities of all classes:  [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Probability of Predicted class :  1.0


In [ ]:
##Random Forest
rf = RandomForestClassifier(random_state = 50)
rf.fit(x_train, y_train)
rfc_y_pred = rf.predict(x_test)
rfc_cm = confusion_matrix(y_test,rfc_y_pred)
rfc_accuracy = accuracy_score(y_test,rfc_y_pred)
print("confusion matrics=",rfc_cm)
print("  ")
print("accuracy=",rfc_accuracy)

confusion matrics= [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
  
accuracy= 0.006134969325153374


In [ ]:


userdata = [[2,0,4,2,5]]
ynewclass = rf.predict(userdata)
ynew = rf.predict_proba(userdata)
print(ynewclass)
print("Probabilities of all classes: ", ynew)
print("Probability of Predicted class : ", np.max(ynew))

['NC010']
Probabilities of all classes:  [[0.   0.01 0.   0.   0.   0.04 0.   0.02 0.   0.   0.   0.   0.   0.21
  0.   0.   0.   0.   0.   0.   0.   0.01 0.   0.   0.38 0.17 0.   0.
  0.   0.   0.   0.08 0.   0.   0.02 0.06]]
Probability of Predicted class :  0.38


In [ ]:
import pickle 
pickle.dump(dtree,open('predict_new.pkl','wb'))

In [ ]:
pickleFile=open("predict_new.pkl","rb")
#importing the model which we created using dt in ml code
regressor=pickle.load(pickleFile) 

In [ ]:
pip install Flask-Cors

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.2.2 -> 22.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
#'cao_score', 'budget', 'location_code', 'interest_code', 'job_domain_code','code'
from flask import Flask, request, render_template
from flask_cors import cross_origin
import sklearn
import pickle
import pandas as pd


app = Flask(__name__)
model = pickle.load(open("predict_new.pkl", "rb"))


@app.route("/")
@cross_origin()
def home():
    return render_template("home.html")

@app.route("/predict", methods = ["GET", "POST"])
@cross_origin()
def predict():
    if request.method == "POST":       


        City = request.form["City"]
        if (City == 'Dublin'):
            location_code = 4

        
        elif (City == 'Carlow'):
            location_code = 1


        elif (City == 'Letterkenny'):
            location_code = 8 


        elif (City == 'Limerick'):
            location_code = 9

        elif (City == 'Athlone'):
            location_code = 0

        elif (City == 'Dundalk'):
            location_code = 5

        elif (City == 'Cork'):
            Citlocation_codey_code = 2

        elif (City == 'Mayo'):
            location_code = 10
            
        elif (City == 'Donegal'):
            location_code = 3

        elif (City == 'Waterford'):
            location_code = 13

        elif (City == 'Wexford'):
            location_code = 14

        elif (City == 'Tipperary'):
            location_code = 12
            
        elif (City == 'Sligo'):
            location_code = 11

        elif (City == 'Galway'):
            location_code = 6


        else:
            location_code = 0

            
        Interest = request.form["Interest"]
        if (Interest == 'Cricket'):
            interest_code = 4

        
        elif (Interest == 'Football'):
            interest_code = 1


        elif (Interest == 'Singing'):
            interest_code = 8 


        elif (Interest == 'Chess'):
            interest_code = 9

        elif (Interest == 'Athletics'):
            interest_code = 0

        elif (Interest == 'Automation'):
            interest_code = 5

        else:
            interest_code = 0

        Job_domain = request.form["Job_domain"]
        
        if (Job_domain == 'IT'):
            job_domain_code = 2

        
        elif (Job_domain == 'HR'):
            job_domain_code = 1


        elif (Job_domain == 'Management'):
            job_domain_code = 4 


        elif (Job_domain == 'Support'):
            job_domain_code = 5

        elif (Interest == 'Finance'):
            job_domain_code = 0

        elif (Job_domain == 'Law'):
            job_domain_code = 3

        else:
            job_domain_code = 0
            


        Budget = request.form["Budget"]
        if (Budget == 'Low'):
            budget = 1

        
        elif (Budget == 'Medium'):
            budget = 2


        elif (Budget == 'High'):
            budget = 3 


        else:
            budget = 1
            

        CAO_Score = request.form["CAO_Score"]
        if (CAO_Score == 'Low'):
            cao_score = 1

        
        elif (CAO_Score == 'Medium'):
            cao_score = 2


        elif (CAO_Score == 'High'):
            cao_score = 3 


        else:
            cao_score = 1
            

        prediction=model.predict([[
            cao_score,
            budget,
            location_code,
            interest_code,
            job_domain_code
            #job_domain_code
            
        ]])

        output=(prediction[0])

        return render_template('home.html',prediction_text="The College recommended is. {}".format(output))


        return render_template("home.html")




if __name__ == "__main__":
    app.run(debug=True,use_reloader=False)

 * Serving Flask app '__main__'
 * Debug mode: on


 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [02/Dec/2022 20:16:24] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [02/Dec/2022 20:16:24] "GET /static/css/styles.css HTTP/1.1" 304 -
c:\Users\rgons\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
127.0.0.1 - - [02/Dec/2022 20:16:32] "POST /predict HTTP/1.1" 500 -
Traceback (most recent call last):
  File "c:\Users\rgons\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "c:\Users\rgons\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "c:\Users\rgons\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_